#!/bin/sh /etc/rc.common
#
# Copyright (c) 2017-2019 The Linux Foundation. All rights reserved.
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

START=00
STOP=95

create_soft_link()
{
	if [ -e /sys/firmware/devicetree/base/AUTO_MOUNT ]; then
		cp -f $*
	elif [ ! -e /sys/firmware/devicetree/base/AUTO_MOUNT ]; then
		ln -s $*
	fi
}

create_caldata_bin()
{
	local board=ap$(echo $(board_name) | awk -F 'ap' '{print$2}')
	local mtdblock=$(find_mtd_part 0:ART)

	local apdk="/tmp"

	if [ -z "$mtdblock" ]; then
		# read from mmc
		mtdblock=$(find_mmc_part 0:ART)
	fi

	[ -n "$mtdblock" ] || return

	# load board.bin
	case "$board" in
		ap-al02-c4*|ap-al02-c6*|ap-al06*|ap-al02-c7*|ap-al02-c8*|ap-al02-c9*|ap-al02-c10*|ap-al02-c11*|ap-al02-c12*|ap-al02-c14*|ap-al02-c15*|ap-al02-c16*|ap-al03-c1*|ap-al03-c2*)
			echo caldata >> /log.log
			AL_BD_FILENAME=/lib/firmware/IPQ9574/bdwlan.bin
			mkdir -p ${apdk}/IPQ9574
			if [ -f "$AL_BD_FILENAME" ]; then
				FILESIZE=$(stat -Lc%s "$AL_BD_FILENAME")
			else
				FILESIZE=131072
			fi
			dd if=${mtdblock} of=${apdk}/IPQ9574/caldata.bin bs=1 count=$FILESIZE skip=4096
			[ -L /lib/firmware/IPQ9574/caldata.bin ] || \
				cp ${apdk}/IPQ9574/caldata.bin /lib/firmware/IPQ9574/caldata.bin

			WKK_FILESIZE=184320
			mkdir -p ${apdk}/qcn9224
			dd if=${mtdblock} of=${apdk}/qcn9224/caldata_1.bin bs=1 count=$WKK_FILESIZE skip=157696
			dd if=${mtdblock} of=${apdk}/qcn9224/caldata_2.bin bs=1 count=$WKK_FILESIZE skip=362496
			dd if=${mtdblock} of=${apdk}/qcn9224/caldata_3.bin bs=1 count=$WKK_FILESIZE skip=567296
			dd if=${mtdblock} of=${apdk}/qcn9224/caldata_4.bin bs=1 count=$WKK_FILESIZE skip=772096
			cp ${apdk}/qcn9224/caldata_1.bin /lib/firmware/qcn9224/caldata_1.bin
			cp ${apdk}/qcn9224/caldata_2.bin /lib/firmware/qcn9224/caldata_2.bin
			cp ${apdk}/qcn9224/caldata_3.bin /lib/firmware/qcn9224/caldata_3.bin
			cp ${apdk}/qcn9224/caldata_4.bin /lib/firmware/qcn9224/caldata_4.bin
		;;
		ap-mi01.1*|ap-mi01.2*|ap-mi01.4*|ap-mi01.6*|ap-mi01.9*)
			MI_BD_FILENAME=/lib/firmware/IPQ5332/bdwlan.bin
			mkdir -p ${apdk}/IPQ5332
			if [ -f "$MI_BD_FILENAME" ]; then
				FILESIZE=$(stat -Lc%s "$MI_BD_FILENAME")
			else
				FILESIZE=131072
			fi
			dd if=${mtdblock} of=${apdk}/IPQ5332/caldata.bin bs=1 count=$FILESIZE skip=4096
			[ -L /lib/firmware/IPQ5332/caldata.bin ] || \
			cp ${apdk}/IPQ5332/caldata.bin /lib/firmware/IPQ5332/caldata.bin

			WKK_FILESIZE=184320
			mkdir -p ${apdk}/qcn9224
			dd if=${mtdblock} of=${apdk}/qcn9224/caldata_1.bin bs=1 count=$WKK_FILESIZE skip=157696
			dd if=${mtdblock} of=${apdk}/qcn9224/caldata_2.bin bs=1 count=$WKK_FILESIZE skip=362496
			cp ${apdk}/qcn9224/caldata_1.bin /lib/firmware/qcn9224/caldata_1.bin
			cp ${apdk}/qcn9224/caldata_2.bin /lib/firmware/qcn9224/caldata_2.bin
		;;
		ap-mi*)
			MI_BD_FILENAME=/lib/firmware/IPQ5332/bdwlan.bin
			mkdir -p ${apdk}/IPQ5332
			if [ -f "$MI_BD_FILENAME" ]; then
				FILESIZE=$(stat -Lc%s "$MI_BD_FILENAME")
			else
				FILESIZE=131072
			fi
			dd if=${mtdblock} of=${apdk}/IPQ5332/caldata.bin bs=1 count=$FILESIZE skip=4096
			[ -L /lib/firmware/IPQ5332/caldata.bin ] || \
			cp ${apdk}/IPQ5332/caldata.bin /lib/firmware/IPQ5332/caldata.bin
		;;
	esac
}

mount_wifi_fw (){
	local emmc_part=""
	local nand_part=""
	local nor_part=""
	local primaryboot=""
	local part_name="0:WIFIFW"
	local ubi_part_name="rootfs"
	local arch=""
	local wifi_on_rootfs=""
	local hw=""
	local board_name
	local fwfolder="/lib/firmware"

	[ -f /tmp/sysinfo/board_name ] && {
		board_name=ap$(cat /tmp/sysinfo/board_name | awk -F 'ap' '{print$2}')
	}

	[ -e /sys/firmware/devicetree/base/AUTO_MOUNT ] && {
		case $board_name in
			ap-mp*)
				fwfolder="/lib/firmware/wifi"
				mkdir -p $fwfolder
			;;
		esac
	}

	if mount | grep -q WIFI_FW; then
		return 0
	fi

	arch=$1
	case "$arch" in
		"IPQ8074")
			hw="hw2.0"
	;;
		"IPQ6018")
			hw="hw1.0"
	;;
		*)
			hw="hw1.0"
	;;
	esac

	local age0=$(cat /proc/boot_info/bootconfig0/age)
	local age1=$(cat /proc/boot_info/bootconfig1/age)
	local bootname="bootconfig1"

	#Try mode
	if [ -e /proc/upgrade_info/trybit ]; then
		if [ -e /proc/upgrade_info/trymode_inprogress ]; then
			if [ $age0 -le $age1 ]; then
				bootname="bootconfig0"
			else
				bootname="bootconfig1"
			fi
		else
			if [ $age1 -ge $age0 ]; then
				bootname="bootconfig1"
			else
				bootname="bootconfig0"
			fi
		fi
	fi

	primaryboot=$(cat /proc/boot_info/$bootname/$part_name/primaryboot)
	if [ $primaryboot -eq 1 ]; then
		part_name="0:WIFIFW_1"
	fi
	if [[ "$arch" == "IPQ6018" ]] || [[ "$arch" == "IPQ5018" ]] || [[ "$arch" == "IPQ9574" ]] || [[ "$arch" == "IPQ5332" ]]; then
		wifi_on_rootfs="1"
	fi

	emmc_part=$(find_mmc_part $part_name 2> /dev/null)
	nor_part=$(cat /proc/mtd | grep -w "WIFIFW" | awk '{print $1}' | sed 's/:$//')
	local nor_flash=`find /sys/bus/spi/devices/*/mtd -name ${nor_part}`
	if [ -n "$wifi_on_rootfs" ]; then
		nand_part=$(find_mtd_part $ubi_part_name 2> /dev/null)
		if [ -n "$nand_part" ]; then
			emmc_part=""
		fi
	else
		nand_part=$(find_mtd_part $part_name 2> /dev/null)
	fi

	mkdir -p /lib/firmware/$arch/WIFI_FW
	if [ -n "$emmc_part" ]; then
		/bin/mount -t squashfs $emmc_part /lib/firmware/$arch/WIFI_FW > /dev/console 2>&1
		if [ $? -eq 0 ]; then
			cp /rom/lib/firmware/$arch/WIFI_FW/*.* /lib/firmware/$arch/WIFI_FW/
		fi
	elif [ -n "$nor_flash" ]; then
		local nor_mtd_part=$(find_mtd_part $part_name 2> /dev/null)
		if [ -n "$nor_mtd_part" ]; then
			/bin/mount -t squashfs $nor_mtd_part /lib/firmware/$arch/WIFI_FW > /dev/console 2>&1
		fi
	elif [ -n "$nand_part" ]; then
                if [ -n "$wifi_on_rootfs" ]; then
                       local PART=$(grep -w  "rootfs" /proc/mtd | awk -F: '{print $1}')
                else
                       local PART=$(grep -w  "WIFIFW" /proc/mtd | awk -F: '{print $1}')
                fi
		ubiattach -p /dev/$PART
		sync
		local ubi_part=$(find_mtd_part wifi_fw 2> /dev/null)
		if [ -n "$ubi_part" ]; then
			/bin/mount -t squashfs $ubi_part /lib/firmware/$arch/WIFI_FW > /dev/console 2>&1
			if [ $? -ne 0 ]; then
				echo "WIFI FW mount failed, retry after 1 sec" > /dev/console 2>&1
				sleep 1
				/bin/mount -t squashfs $ubi_part /lib/firmware/$arch/WIFI_FW > /dev/console 2>&1
				if [ $? -ne 0 ]; then
					echo "CRITICAL:WIFI FW mount failed, after 1 sec retry" > /dev/console 2>&1
					echo $(cat /proc/mtd) > /dev/console 2>&1
					return -1
				fi
			fi
		fi
	fi
	if [ -f /lib/firmware/$arch/WIFI_FW/q6_fw.mdt ] || ([ -f /lib/firmware/$arch/WIFI_FW/q6_fw0.mdt ] && [ -f /lib/firmware/$arch/WIFI_FW/q6_fw1.mdt ]); then
		echo " WIFI FW mount is successful" > /dev/console 2>&1
	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn9000 ]; then
		cd  $fwfolder && mkdir -p qcn9000 && mkdir -p /vendor/firmware/qcn9000
		cd qcn9000 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9000/*.* .
		cd /vendor/firmware/qcn9000 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9000/Data.msc .
		mkdir -p /lib/firmware/qcn9000 && cd /lib/firmware/qcn9000 && create_soft_link /lib/firmware/$arch/WIFI_FW/qcn9000/qdss* .
	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn9224 ]; then
		cd  $fwfolder && mkdir -p qcn9224 && mkdir -p /vendor/firmware/qcn9224
		cd qcn9224 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9224/*.* .
		cd /vendor/firmware/qcn9224 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9224/Data.msc .
		ln -s /lib/firmware/$arch/WIFI_FW/qcn9224/Data_dualmac.msc .
		mkdir -p /lib/firmware/qcn9224 && cd /lib/firmware/qcn9224 && create_soft_link /lib/firmware/$arch/WIFI_FW/qcn9224/qdss* .
	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn9100 ]; then
		cd $fwfolder && mkdir -p qcn9100 && mkdir -p /vendor/firmware/qcn9100
		cd qcn9100 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9100/*.* . && ln -s /lib/firmware/$arch/WIFI_FW/q6_fw.* .
		cd /vendor/firmware/qcn9100 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9100/Data.msc .
		mkdir -p /lib/firmware/qcn9100 && cd /lib/firmware/qcn9100 && create_soft_link /lib/firmware/$arch/WIFI_FW/qcn9100/qdss* .
	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn6122 ]; then
		cd $fwfolder && mkdir -p qcn6122 && mkdir -p /vendor/firmware/qcn6122
		cd qcn6122 && ln -s /lib/firmware/$arch/WIFI_FW/qcn6122/*.* . && ln -s /lib/firmware/$arch/WIFI_FW/q6_fw.* .
		cd /vendor/firmware/qcn6122 && ln -s /lib/firmware/$arch/WIFI_FW/qcn6122/Data.msc .
		mkdir -p /lib/firmware/qcn6122 && cd /lib/firmware/qcn6122 && create_soft_link /lib/firmware/$arch/WIFI_FW/qcn6122/qdss* .
	elif [ -d /lib/firmware/$arch/WIFI_FW/qcn9100 ]; then
		cd $fwfolder && mkdir -p qcn6122 && mkdir -p /vendor/firmware/qcn6122
		cd qcn6122 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9100/*.* . && ln -s /lib/firmware/$arch/WIFI_FW/q6_fw.* .
		cd /vendor/firmware/qcn6122 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9100/Data.msc .
		mkdir -p /lib/firmware/qcn6122 && cd /lib/firmware/qcn6122 && create_soft_link /lib/firmware/$arch/WIFI_FW/qcn9100/qdss* .
	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn9160 ]; then
		cd $fwfolder && mkdir -p qcn9160 && mkdir -p /vendor/firmware/qcn9160
		cd qcn9160 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9160/*.* . && ln -s /lib/firmware/$arch/WIFI_FW/q6_fw.* .
		cd /vendor/firmware/qcn9160 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9160/Data.msc .
		mkdir -p /lib/firmware/qcn9160 && cd /lib/firmware/qcn9160 && create_soft_link /lib/firmware/$arch/WIFI_FW/qcn9160/qdss* .
	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn6432 ]; then
		cd $fwfolder && mkdir -p qcn6432 && mkdir -p /vendor/firmware/qcn6432
		cd qcn6432 && ln -s /lib/firmware/$arch/WIFI_FW/qcn6432/*.* . && ln -s /lib/firmware/$arch/WIFI_FW/q6_fw.* .
		cd /vendor/firmware/qcn6432 && ln -s /lib/firmware/$arch/WIFI_FW/qcn6432/Data.msc .
		mkdir -p /lib/firmware/qcn6432 && cd /lib/firmware/qcn6432 && create_soft_link /lib/firmware/$arch/WIFI_FW/qcn6432/qdss* .
        fi

	mkdir -p $fwfolder/$arch
	cd  $fwfolder/$arch && ln -s /lib/firmware/$arch/WIFI_FW/*.* .
	cd  /lib/firmware/$arch && create_soft_link /lib/firmware/$arch/WIFI_FW/qdss* .

	if [ -e /sys/firmware/devicetree/base/MP_512 ] || [ -e /sys/firmware/devicetree/base/MP_256 ]; then
		#qcn9224 INI file would have all QCN9224 RDP's info, so first priority for qcn9224 file if it exists
		if [ -f /lib/firmware/$arch/WIFI_FW/qcn9224/firmware_rdp_feature_512P.ini ]; then
			cd /lib/firmware
			create_soft_link /lib/firmware/$arch/WIFI_FW/qcn9224/firmware_rdp_feature_512P.ini .
		elif [ -f /lib/firmware/$arch/WIFI_FW/firmware_rdp_feature_512P.ini ]; then
			cd /lib/firmware
			create_soft_link /lib/firmware/$arch/WIFI_FW/firmware_rdp_feature_512P.ini .
		elif [ -f /lib/firmware/$arch/WIFI_FW/qcn9000/firmware_rdp_feature_512P.ini ]; then
			cd /lib/firmware
			create_soft_link /lib/firmware/$arch/WIFI_FW/qcn9000/firmware_rdp_feature_512P.ini .
		fi
	else
		#qcn9224 INI file would have all QCN9224 RDP's info, so first priority for qcn9224 file if it exists
		if [ -f /lib/firmware/$arch/WIFI_FW/qcn9224/firmware_rdp_feature.ini ]; then
			cd /lib/firmware
			create_soft_link /lib/firmware/$arch/WIFI_FW/qcn9224/firmware_rdp_feature.ini .
		elif [ -f /lib/firmware/$arch/WIFI_FW/firmware_rdp_feature.ini ]; then
			cd /lib/firmware
			create_soft_link /lib/firmware/$arch/WIFI_FW/firmware_rdp_feature.ini .
		elif [ -f /lib/firmware/$arch/WIFI_FW/qcn9000/firmware_rdp_feature.ini ]; then
			cd /lib/firmware
			create_soft_link /lib/firmware/$arch/WIFI_FW/qcn9000/firmware_rdp_feature.ini .
		fi
	fi

	. /lib/read_caldata_to_fs.sh
	do_load_ipq4019_board_bin

	if [ -e /lib/firmware/$arch/WIFI_FW/board-2.bin ]; then

		create_caldata_bin
		case "$arch" in
			IPQ5332)
				mkdir -p /lib/firmware/ath12k/$arch/$hw
				cd /lib/firmware/ath12k/$arch/$hw/
				;;
			*)
				mkdir -p /lib/firmware/ath11k/$arch/$hw
				cd /lib/firmware/ath11k/$arch/$hw/
				;;
		esac
		ln -s /lib/firmware/$arch/WIFI_FW/board-2.bin .
		ln -s /lib/firmware/$arch/caldata.bin .
		ln -s /lib/firmware/$arch/qdss_trace_config.bin .
	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn9000 ]; then
		if [ -e /lib/firmware/$arch/WIFI_FW/qcn9000/board-2.bin ]; then
			mkdir -p /lib/firmware/ath11k/QCN9074/hw1.0/
			cd /lib/firmware/ath11k/QCN9074/hw1.0/
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9000/board-2.bin .
			ln -s /tmp/qcn9000/caldata*.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9000/m3.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9000/amss.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9000/qdss_trace_config.bin .
		fi
	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn9100 ]; then
		if [ -e /lib/firmware/$arch/WIFI_FW/qcn9100/board-2.bin ]; then
			mkdir -p /lib/firmware/ath11k/qcn9100/hw1.0/
			cd /lib/firmware/ath11k/qcn9100/hw1.0/
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9100/board-2.bin .
			ln -s /lib/firmware/qcn9100/caldata*.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9100/qdss_trace_config.bin .
		fi
	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn6122 ]; then
		if [ -e /lib/firmware/$arch/WIFI_FW/qcn6122/board-2.bin ]; then
			mkdir -p /lib/firmware/ath11k/qcn6122/hw1.0/
			cd /lib/firmware/ath11k/qcn6122/hw1.0/
			ln -s /lib/firmware/$arch/WIFI_FW/qcn6122/board-2.bin .
			ln -s /lib/firmware/qcn6122/caldata*.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn6122/qdss_trace_config.bin .
		fi
	elif [ -d /lib/firmware/$arch/WIFI_FW/qcn9100 ]; then
		if [ -e /lib/firmware/$arch/WIFI_FW/qcn9100/board-2.bin ]; then
			mkdir -p /lib/firmware/ath11k/qcn6122/hw1.0/
			cd /lib/firmware/ath11k/qcn6122/hw1.0/
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9100/board-2.bin .
			ln -s /lib/firmware/qcn9100/caldata*.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9100/qdss_trace_config.bin .
		fi
	elif [ -d /lib/firmware/$arch/WIFI_FW/qcn9224 ]; then
		if [ -e /lib/firmware/$arch/WIFI_FW/qcn9224/board-2.bin ]; then
			mkdir -p /lib/firmware/ath12k/QCN92XX/hw1.0/
			cd /lib/firmware/ath12k/QCN92XX/hw1.0/
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9224/m3.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9224/amss.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9224/amss_dualmac.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9224/board-2.bin .
			if [ -e /lib/firmware/$arch/WIFI_FW/qcn9224/regdb.bin ]; then
				ln -s /lib/firmware/$arch/WIFI_FW/qcn9224/regdb.bin .
			fi
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9224/qdss_trace_config.bin .
			case $board_name in
				ap-al02-c4)
					#caldata_2.bin --> PCI1 2.4 GHz
					if [ -e /lib/firmware/qcn9224/caldata_2.bin ]; then
						ln -s /lib/firmware/qcn9224/caldata_2.bin cal-pci-0002:01:00.0.bin
					fi

					#caldata_3.bin --> PCI2 6 GHz
					if [ -e /lib/firmware/qcn9224/caldata_3.bin ]; then
						ln -s /lib/firmware/qcn9224/caldata_3.bin cal-pci-0003:01:00.0.bin
					fi

					#caldata_4.bin --> PCI3 5 GHz
					if [ -e /lib/firmware/qcn9224/caldata_4.bin ]; then
						ln -s /lib/firmware/qcn9224/caldata_4.bin cal-pci-0004:01:00.0.bin
					fi
				;;
				ap-al02-c6)
					#caldata_3.bin --> PCI2 6 GHz
					if [ -e /lib/firmware/qcn9224/caldata_3.bin ]; then
						ln -s /lib/firmware/qcn9224/caldata_3.bin cal-pci-0003:01:00.0.bin
					fi

					#caldata_4.bin --> PCI3 5 GHz
					if [ -e /lib/firmware/qcn9224/caldata_4.bin ]; then
						ln -s /lib/firmware/qcn9224/caldata_4.bin cal-pci-0004:01:00.0.bin
					fi
				;;
				ap-al06)
                                        #caldata_3.bin --> PCI2 6 GHz
                                        if [ -e /lib/firmware/qcn9224/caldata_3.bin ]; then
                                                ln -s /lib/firmware/qcn9224/caldata_3.bin cal-pci-0003:01:00.0.bin
                                        fi

                                        #caldata_4.bin --> PCI3 5 GHz
                                        if [ -e /lib/firmware/qcn9224/caldata_4.bin ]; then
                                                ln -s /lib/firmware/qcn9224/caldata_4.bin cal-pci-0004:01:00.0.bin
                                        fi
                                ;;
				ap-al02-c9)
					if [ -e /lib/firmware/qcn9224/caldata_1.bin ]; then
						ln -s /lib/firmware/qcn9224/caldata_1.bin cal-pci-0001:01:00.0.bin
					fi

					if [ -e /lib/firmware/qcn9224/caldata_3.bin ]; then
						ln -s /lib/firmware/qcn9224/caldata_3.bin cal-pci-0003:01:00.0.bin
					fi
				;;
				ap-mi01.2)
					#caldata.bin --> ahb 2GHz
					if [ -e /lib/firmware/IPQ5332/caldata.bin ]; then
						ln -s /lib/firmware/IPQ5332/caldata.bin cal-ahb-c000000.wifi.bin
					fi

					#caldata_1.bin --> cal-pci-0001:01:00.0.bin
					if [ -e /lib/firmware/qcn9224/caldata_1.bin ]; then
						ln -s /lib/firmware/qcn9224/caldata_1.bin cal-pci-0001:01:00.0.bin
					fi

					#caldata_2.bin --> cal-pci-0001:01:00.0.bin
					if [ -e /lib/firmware/qcn9224/caldata_2.bin ]; then
						ln -s /lib/firmware/qcn9224/caldata_2.bin cal-pci-0000:01:00.0.bin
					fi
				;;
				ap-mi01.6)
					#caldata.bin --> ahb 2GHz
					if [ -e /lib/firmware/IPQ5332/caldata.bin ]; then
						ln -s /lib/firmware/IPQ5332/caldata.bin cal-ahb-c000000.wifi.bin
					fi

					#caldata_1.bin --> cal-pci-0001:01:00.0.bin
					if [ -e /lib/firmware/qcn9224/caldata_1.bin ]; then
						ln -s /lib/firmware/qcn9224/caldata_1.bin cal-pci-0001:01:00.0.bin
					fi
				;;
				ap-mi01.9)
					#caldata_1.bin --> cal-pci-0001:01:00.0.bin
					if [ -e /lib/firmware/qcn9224/caldata_1.bin ]; then
						ln -s /lib/firmware/qcn9224/caldata_1.bin cal-pci-0001:01:00.0.bin
					fi
					#caldata_2.bin --> cal-pci-0001:01:00.0.bin
					if [ -e /lib/firmware/qcn9224/caldata_2.bin ]; then
						ln -s /lib/firmware/qcn9224/caldata_2.bin cal-pci-0000:01:00.0.bin
					fi
				;;
				*)
					#No sym links
				;;
			esac
		fi
	fi

	mkdir -p /vendor/firmware/$arch
	cd /vendor/firmware/$arch && ln -s /lib/firmware/$arch/WIFI_FW/Data.msc .
}

mount_adsp_fw (){
	local emmc_part=""
	local nand_part=""
	local nor_part=""
	local ubi_part_name="rootfs"
	local part_name="0:ADSPFW"
	local arch=""

	if mount | grep -q ADSP_FW; then
		return 0
	fi

	arch=$1
	emmc_part=$(find_mmc_part $part_name 2> /dev/null)
	nor_part=$(cat /proc/mtd | grep ADSPFW | awk '{print $1}' | sed 's/:$//')
	local nor_flash=`find /sys/bus/spi/devices/*/mtd -name ${nor_part}`
	nand_part=$(find_mtd_part $ubi_part_name 2> /dev/null)
	mkdir -p /lib/firmware/$arch/ADSP_FW

	if [ -n "$emmc_part" ]; then
		/bin/mount -t squashfs $emmc_part /lib/firmware/$arch/ADSP_FW > /dev/console 2>&1
		[ -f /rom/lib/firmware/$arch/ADSP_FW/q6_fw.mdt ] && cp /rom/lib/firmware/$arch/ADSP_FW/*.* /lib/firmware/$arch/ADSP_FW/
	elif [ -n "$nor_flash" ]; then
		local nor_mtd_part=$(find_mtd_part $part_name 2> /dev/null)
		if [ -n "$nor_mtd_part" ]; then
			/bin/mount -t squashfs $nor_mtd_part /lib/firmware/$arch/ADSP_FW > /dev/console 2>&1
		fi
	elif [ -n "$nand_part" ]; then
		local PART=$(grep -w  "rootfs" /proc/mtd | awk -F: '{print $1}')
		ubiattach -p /dev/$PART
		sync
		local ubi_part=$(find_mtd_part adsp_fw 2> /dev/null)
		if [ -n "$ubi_part" ]; then
			/bin/mount -t squashfs $ubi_part /lib/firmware/$arch/ADSP_FW > /dev/console 2>&1
		fi
	fi

	if [ -f /lib/firmware/$arch/ADSP_FW/image/adsp.mdt ]; then
		echo " ADSP FW mount is successful" > /dev/console 2>&1
	fi

	cd  /lib/firmware/$arch &&  ln -s ADSP_FW/image/*.* .
	[ -d /lib/firmware/$arch/ADSP_FW/dspso ] && ln -s /lib/firmware/$arch/ADSP_FW/dspso /dsp
}

mount_bt_fw (){
	local emmc_part=""
	local nand_part=""
	local nor_part=""
	local ubi_part_name="rootfs"
	local part_name="0:BTFW"
	local arch=""
	local nor_flash=""
	local nor_mtd_part=""
	local PART=""
	local ubi_part=""

	if mount | grep -q BT_FW; then
		return 0;
	fi

	arch=$1
	emmc_part=$(find_mmc_part $part_name 2> /dev/null)
	nor_part=$(cat /proc/mtd | grep BTFW | awk '{print $1}' | sed 's/:$//')
	nor_flash=`find /sys/bus/spi/devices/*/mtd -name ${nor_part}`
	nand_part=$(find_mtd_part $ubi_part_name 2> /dev/null)

	mkdir -p /lib/firmware/$arch/BT_FW

	if [ -n "$emmc_part" ]; then
		/bin/mount -t squashfs $emmc_part /lib/firmware/$arch/BT_FW > /dev/console 2>&1
		[ -f /rom/lib/firmware/$arch/BT_FW/bt_fw.mdt ] && cp /rom/lib/firmware/$arch/BT_FW/*.* /lib/firmware/$arch/BT_FW/
	elif [ -n "$nor_flash" ]; then
		nor_mtd_part=$(find_mtd_part $part_name 2> /dev/null)
		/bin/mount -t squashfs $nor_mtd_part /lib/firmware/$arch/BT_FW > /dev/console 2>&1
	elif [ -n "$nand_part" ]; then
		PART=$(grep -w  "rootfs" /proc/mtd | awk -F: '{print $1}')
		ubiattach -p /dev/$PART
		sync
		ubi_part=$(find_mtd_part bt_fw 2> /dev/null)
		/bin/mount -t squashfs $ubi_part /lib/firmware/$arch/BT_FW > /dev/console 2>&1
	fi

	if [ -f /lib/firmware/$arch/BT_FW/image/bt_fw_patch.mdt ]; then
		echo "BT FW mount is successful" > /dev/console 2>&1
		mkdir /tmp/BT_FW &&  cp -r /lib/firmware/$arch/BT_FW/image/ /tmp/BT_FW
		umount /lib/firmware/$arch/BT_FW
	else
		echo "BT FW mount is failed" > /dev/console 2>&1
	fi

	cd /lib/firmware/$arch && ln -s /tmp/BT_FW/image/*.* .
}

boot() {
 . /lib/functions/system.sh
	local platform=$(grep -o "IPQ.*" /proc/device-tree/model | awk -F/ '{print $1}')
	local board=$(grep -o "IPQ.*" /proc/device-tree/model | awk -F/ '{print $2}')

	if [ "$platform" == "IPQ807x" ]; then
		mount_wifi_fw "IPQ8074"
	elif [ "$platform" == "IPQ8074" ]; then
		mount_wifi_fw "IPQ8074"
	elif [ "$platform" == "IPQ9574" ]; then
		mount_wifi_fw "IPQ9574"
	elif [ "$platform" == "IPQ6018" ]; then
		mount_wifi_fw "IPQ6018"
		case "$board" in
			AP-CP01*)
				mount_adsp_fw "IPQ6018"
				;;
		esac
	elif [ "$platform" == "IPQ5018" ]; then
		mount_bt_fw "IPQ5018"
		mount_wifi_fw "IPQ5018"
	elif [ "$platform" == "IPQ5332" ]; then
		mount_wifi_fw "IPQ5332"
	else
		echo "\nInvalid Target"
	fi
}

stop_wifi_fw() {
	local emmc_part=""
	local nand_part=""
	local nor_part=""
	local primaryboot=""
	local part_name="0:WIFIFW"
	local wifi_on_rootfs=""
	local nor_flash=""
	arch=$1

	if [[ "$arch" == "IPQ6018" ]] || [[ "$arch" == "IPQ5018" ]]; then
		part_name="rootfs"
		wifi_on_rootfs="1"
	fi

	local age0=$(cat /proc/boot_info/bootconfig0/age)
	local age1=$(cat /proc/boot_info/bootconfig1/age)
	local bootname="bootconfig1"

	#Try mode
	if [ -e /proc/upgrade_info/trybit ]; then
		if [ $age1 -ge $age0 ]; then
			bootname="bootconfig1"
		else
			bootname="bootconfig0"
		fi
	fi

	primaryboot=$(cat /proc/boot_info/$bootname/$part_name/primaryboot)
	if [ $primaryboot -eq 1 ]; then
		part_name="${part_name}_1"
	fi

	emmc_part=$(find_mmc_part $part_name 2> /dev/null)
	nor_part=$(cat /proc/mtd | grep -w "WIFIFW" | awk '{print $1}' | sed 's/:$//')
	if [ -n "$nor_part" ]; then
		nor_flash=`find /sys/bus/spi/devices/*/mtd -name ${nor_part}`
	fi
	nand_part=$(find_mtd_part $part_name 2> /dev/null)
	if [ -n "$emmc_part" ]; then
		umount /lib/firmware/$arch/WIFI_FW
	elif [ -n "$nor_flash" ]; then
		local nor_mtd_part=$(find_mtd_part $part_name 2> /dev/null)
		umount /lib/firmware/$arch/WIFI_FW
	elif [ -n "$nand_part" ]; then
		umount /lib/firmware/$arch/WIFI_FW
		if [ -z "$wifi_on_rootfs" ]; then
			local PART=$(grep -w  "WIFIFW" /proc/mtd | awk -F: '{print $1}')
			ubidetach -f -p  /dev/$PART
			sync
		fi
	fi
}

stop_adsp_fw() {
	local emmc_part=""
	local nand_part=""
	local nor_part=""
	local part_name="0:ADSPFW"
	arch=$1

	emmc_part=$(find_mmc_part $part_name 2> /dev/null)
	nor_part=$(cat /proc/mtd | grep ADSPFW | awk '{print $1}' | sed 's/:$//')
	local nor_flash=`find /sys/bus/spi/devices/*/mtd -name ${nor_part}`
	nand_part=$(find_mtd_part rootfs 2> /dev/null)
	if [ -n "$emmc_part" ]; then
		umount /lib/firmware/$arch/ADSP_FW
	elif [ -n "$nor_flash" ]; then
		local nor_mtd_part=$(find_mtd_part $part_name 2> /dev/null)
		umount /lib/firmware/$arch/ADSP_FW
	elif [ -n "$nand_part" ]; then
		umount /lib/firmware/$arch/ADSP_FW
	fi
}

stop_bt_fw() {
	local emmc_part=""
	local nand_part=""
	local nor_part=""
	local part_name="0:BTFW"
	local nor_mtd_part=""
	local nor_flash=""
	arch=$1

	emmc_part=$(find_mmc_part $part_name 2> /dev/null)
	nor_part=$(cat /proc/mtd | grep BTFW | awk '{print $1}' | sed 's/:$//')
	nor_flash=`find /sys/bus/spi/devices/*/mtd -name ${nor_part}`
	nand_part=$(find_mtd_part rootfs 2> /dev/null)
	if [ -n "$emmc_part" ]; then
		umount /lib/firmware/$arch/BT_FW
	elif [ -n "$nor_flash" ]; then
		nor_mtd_part=$(find_mtd_part $part_name 2> /dev/null)
		umount /lib/firmware/$arch/BT_FW
	elif [ -n "$nand_part" ]; then
		umount /lib/firmware/$arch/BT_FW
	fi
}

stop() {
	local platform=$(grep -o "IPQ.*" /proc/device-tree/model | awk -F/ '{print $1}')
	local board=$(grep -o "IPQ.*" /proc/device-tree/model | awk -F/ '{print $2}')

	if [ "$platform" == "IPQ807x" ]; then
		stop_wifi_fw "IPQ8074"
	elif [ "$platform" == "IPQ8074" ]; then
		stop_wifi_fw "IPQ8074"
	elif [ "$platform" == "IPQ9574" ]; then
		stop_wifi_fw "IPQ9574"
	elif [ "$platform" == "IPQ6018" ]; then
		stop_wifi_fw "IPQ6018"
		case "$board" in
			AP-CP01*)
				stop_adsp_fw "IPQ6018"
				;;
		esac
	elif [ "$platform" == "IPQ5018" ]; then
		stop_wifi_fw "IPQ5018"
		stop_bt_fw "IPQ5018"
	elif [ "$platform" == "IPQ5332" ]; then
		stop_wifi_fw "IPQ5332"
	else
		echo "\nInvalid Target"
		return 0
	fi
	return 0
}
